spring:
  profiles:
    active: local
  application:
    name: road-gateway

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true


logging:
  level:
    org.springframework:
      cloud: DEBUG

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
        exclude: ""
    web:
      exposure:
        include: "*"
        exclude: ""
  endpoint:
    health:
      show-details: always

---
spring:
  profiles:
    on-profile: prod
  application:
    name: road-gateway

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework:
      cloud: INFO